Week5/TodoList/Models/Assignment.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TodoList.Models
{
    [Table("Assignment")]
    public partial class Assignment
    {
        public Assignment()
        {
            TodoTasks = new HashSet<TodoTask>();
        }

        [Key]
        [Column("assigmentId")]
        public int AssigmentId { get; set; }
        [Column("createdBy")]
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column("assignedTo")]
        [StringLength(50)]
        [Unicode(false)]
        public string AssignedTo { get; set; }

        [InverseProperty("Assignment")]
        public virtual ICollection<TodoTask> TodoTasks { get; set; }
    }
}

Week5/TodoList/Models/ErrorViewModel.cs
namespace TodoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Week5/TodoList/Models/ToDoLIstContext.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TodoList.Models
{
    public partial class ToDoLIstContext : DbContext
    {
        public ToDoLIstContext()
        {
        }

        public ToDoLIstContext(DbContextOptions<ToDoLIstContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<TodoTask> TodoTasks { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=SPARESCHOOL3\\SQLEXPRESS;Initial Catalog=ToDoLIst;Integrated Security=True;TrustServerCertificate=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Assignment>(entity =>
            {
                entity.HasKey(e => e.AssigmentId)
                    .HasName("PK__Assignme__7965E16A058608DF");
            });

            modelBuilder.Entity<TodoTask>(entity =>
            {
                entity.HasOne(d => d.Assignment)
                    .WithMany(p => p.TodoTasks)
                    .HasForeignKey(d => d.AssignmentId)
                    .HasConstraintName("FK__TodoTask__assign__38996AB5");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Week5/TodoList/Models/TodoTask.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TodoList.Models
{
    [Table("TodoTask")]
    public partial class TodoTask
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("date", TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Column("assignmentId")]
        public int? AssignmentId { get; set; }
        [Column("done")]
        public bool? Done { get; set; }

        [ForeignKey("AssignmentId")]
        [InverseProperty("TodoTasks")]
        public virtual Assignment Assignment { get; set; }
    }
}

Week5/TodoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TodoList.Models;

namespace TodoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Week5/TodoList/Controllers/ToDoTaskController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using TodoList.Contracts;
using TodoList.Models;
using TodoList.Services;

namespace TodoList.Controllers
{
    public class ToDoTaskController : Controller
    {
        private readonly IToDoTaskServices _IToDoTaskServices;

        public ToDoTaskController(IToDoTaskServices toDoTaskServices)
        {
            _IToDoTaskServices = toDoTaskServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //List<TodoTask> tasks = new List<TodoTask>();

            var result = _IToDoTaskServices.AllTasks();
           
            //if (tasks.Count > 0)
            //{
            //    return View(tasks);
            //}

            return View(result);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TodoTask task)
        {
            _IToDoTaskServices.CreateTask(task);
            
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            TodoTask detailTask = new TodoTask();

            detailTask = _IToDoTaskServices.DetailsTask(id);

            return View(detailTask);
        }

        public IActionResult Edit(int id)
        {
            TodoTask editTask = new TodoTask();

            editTask = _IToDoTaskServices.EditViewTask(id);

            return View(editTask);
        }

        [HttpPost]
        public IActionResult Edit(TodoTask model)
        {
            model =  _IToDoTaskServices.EditTask(model);

            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        { 
            _IToDoTaskServices.DeleteTask(id);

            return RedirectToAction("Index");
        }
    }
}

Week5/TodoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Week5/TodoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoTask" asp-action="Index">ToDoTasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TodoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Week5/TodoList/Views/ToDoTask/Create.cshtml
@model TodoList.Models.TodoTask

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Week5/TodoList/Views/ToDoTask/Details.cshtml
@model TodoList.Models.TodoTask

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TodoTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Done)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Done)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Week5/TodoList/Views/ToDoTask/Edit.cshtml
@model TodoTask


@{
    ViewBag.Title = "Edit";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input hidden asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
            </div>
            <div class="form-group form-check">
                <label asp-for="Done" class="form-group form-check">
                    <input form-group form-check asp-for="Done" /> @Html.DisplayNameFor(model => model.Done)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Week5/TodoList/Views/ToDoTask/Index.cshtml
@model IEnumerable<TodoTask>

@{
}

<h1>ToDoList</h1>

<p>
    @Html.ActionLink("Create Task", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assignment.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assignment.AssignedTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Done)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => task.Id)
                </td>
                <td>
                    @task.Name
                </td>
                <td>
                    @task.Date
                </td>
                <td>
                    @task.Assignment.CreatedBy
                </td>
                <td>
                    @task.Assignment.AssignedTo
                </td>
                <td>
                    @task.Done
                </td>
                <td>
                    <a asp-controller="ToDoTask" asp-action="Edit" asp-route-id="@task.Id" class="btn btn-warning">Edit</a>
                </td>
                <td>
                    <a asp-controller="ToDoTask" asp-action="Details" asp-route-id="@task.Id" class="btn btn-warning">Details</a>
                </td>
                 <td>
                    <form class="mt-2" asp-controller="ToDoTask" asp-action="Delete" asp-route-id="@task.Id">
                        <div class="d-grid gap-2">
                            <input type="submit" value="Delete" class="btn btn-danger mb-2"
                               onclick="return confirm('Are you sure you want to delere post: @task.Name')" />
                        </div>
                    </form>
                </td>
              
            </tr>
            
        }
    </tbody>

</table>